### ISSUE TITLE
AttributeError: 'Unknown' object has no attribute 'name'

### ISSUE THREAD

**Issue by exhuma** [PyCQA/pylint#1622]
### Steps to reproduce

I was able to find the issue: I have a class which has a property, and that property is also used in `__hash__`. It seems that this causes the issue. Here is a minimal implementation which reproduces this:

```
class MyObject:

    def __init__(self, data=None):
        self._raw_data = data

    def __hash__(self):
        return self.data.__hash__()

    @property
    def data(self):
        return self._raw_data * 2  # not actual code, just illustrative

    @data.setter
    def data(self, value):
        self._raw_data = value / 2  # not actual code, just illustrative
```

### Current behavior

When running pylint on the file above, it crashes with the traceback below:

```
Traceback (most recent call last):
  File "./env/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/users/malbert/work/ipbase/core/env/lib/python3.5/site-packages/pylint/checkers/stdlib.py", line 185, in visit_call
    if inferred.root().name == OPEN_MODULE:
AttributeError: 'Unknown' object has no attribute 'name'
```

### Expected behavior

No traceback.

### pylint --version output

```
pylint 1.7.2,
astroid 1.5.3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
```

**Comment by rogalski** [comment]
Solved in cb8ebdb02ba208a8c38bba622bd85ad37a7a2c21 ?

**Comment by exhuma** [comment]
I checked out cb8ebdb and I still get the same error. Even with the example I gave above.

**Comment by PCManticore** [comment]
Sorry, I didn't get a chance to fix this, the comment that was linked was somewhat related, but it was not intended to fix this problem

**Comment by brycepg** [comment]
I can't repro this after pylint==2.0

**Comment by PCManticore** [comment]
Thanks for confirming this Bryce, we can close this.
