### ISSUE TITLE
ImportError: cannot import name 'UnknownMessageError' from 'pylint.utils' 

### ISSUE THREAD

**Issue by blairg23** [PyCQA/pylint#3126]
I'm trying to run `pylint` on my Django project using the command: `pylint --load-plugins pylint_django components integrations server` where `components`, `integrations`, and `server` are the three primary Django app locations. I fixed all the linting failure messages and ran the command again, which presented the error message: `ImportError: cannot import name 'UnknownMessageError' from 'pylint.utils' ` The full traceback is shown below:

### Steps to reproduce
1. `pylint --load-plugins pylint_django <django_app_names>`

### Current behavior
```
$ pylint --load-plugins pylint_django components integrations server
Traceback (most recent call last):
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint_plugin_utils\__init__.py", line 3, in <module>
    from pylint.utils import UnknownMessage
ImportError: cannot import name 'UnknownMessage' from 'pylint.utils' (c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint\utils\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Desktop\sandboxes\python\test-project\.tox\lint\Scripts\pylint.EXE\__main__.py", line 9, in <module>
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint\__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint\lint.py", line 1639, in __init__
    linter.load_plugin_modules(self._plugins)
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint\lint.py", line 660, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\astroid\modutils.py", line 198, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\astroid\modutils.py", line 241, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint_django\__init__.py", line 6, in <module>
    from pylint_django import plugin
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint_django\plugin.py", line 3, in <module>
    from pylint_plugin_utils import get_checker
  File "c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint_plugin_utils\__init__.py", line 5, in <module>
    from pylint.utils import UnknownMessageError as UnknownMessage
ImportError: cannot import name 'UnknownMessageError' from 'pylint.utils' (c:\users\username\desktop\sandboxes\python\test-project\.tox\lint\lib\site-packages\pylint\utils\__init__.py)
```

### Expected behavior
Successful linting.

### pylint --version output
`pylint 2.3.1`
`astroid 2.2.5`
`Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]`

**Comment by PNNutkung** [comment]
I also have the same issue.

Dependencies Version
---
`pylint 2.4.0`  
`pylint-django 2.0.11`  
`Python 3.7.4 (default, Jul  9 2019, 18:13:23)`

**Comment by PCManticore** [comment]
pylint 2.4.0 reorganised some internal files a bit, and `pylint-django` is not up-to-date with that reorganisation. This will be eventually fixed by https://github.com/PyCQA/pylint-plugin-utils/pull/16.

**Comment by PedanticHacker** [comment]
This issue is still not resolved. I just can't use `prospector` in my CLI because of this exact error, and `pylint` is integrated into `prospector`.

**Comment by PedanticHacker** [comment]
@DanielNoord, I am using `pylint 2.17.1` and `prospector 1.9.0`.

**Comment by DanielNoord** [comment]
And which version of `pylint-django`?

**Comment by Pierre-Sassoulas** [comment]
We don't have ``from pylint.utils import UnknownMessageError as UnknownMessage`` in ``pylint\utils\__init__.py`` in pylint 2.17.1. It's very likely that you're not running in the same environment you think you are.

**Comment by PedanticHacker** [comment]
@DanielNoord, let me give you the full list:

```
Requirement already satisfied: prospector in c:\program files\python 3.11\lib\site-packages (1.9.0)
Requirement already satisfied: GitPython<4.0.0,>=3.1.27 in c:\program files\python 3.11\lib\site-packages (from prospector) (3.1.31)
Requirement already satisfied: PyYAML in c:\program files\python 3.11\lib\site-packages (from prospector) (6.0)
Requirement already satisfied: dodgy<0.3.0,>=0.2.1 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.2.1)
Requirement already satisfied: flake8<6.0.0 in c:\program files\python 3.11\lib\site-packages (from prospector) (5.0.4)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.7.0)
Requirement already satisfied: packaging in c:\program files\python 3.11\lib\site-packages (from prospector) (23.0)
Requirement already satisfied: pep8-naming<=0.10.0,>=0.3.3 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.10.0)
Requirement already satisfied: pycodestyle>=2.9.0 in c:\program files\python 3.11\lib\site-packages (from prospector) (2.9.1)
Requirement already satisfied: pydocstyle>=2.0.0 in c:\program files\python 3.11\lib\site-packages (from prospector) (6.3.0)
Requirement already satisfied: pyflakes<3,>=2.2.0 in c:\program files\python 3.11\lib\site-packages (from prospector) (2.5.0)
Requirement already satisfied: pylint>=2.8.3 in c:\program files\python 3.11\lib\site-packages (from prospector) (2.17.1)
Requirement already satisfied: pylint-celery==0.3 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.3)
Requirement already satisfied: pylint-django<2.6,>=2.5 in c:\program files\python 3.11\lib\site-packages (from prospector) (2.5.3)
Requirement already satisfied: pylint-flask==0.6 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.6)
Requirement already satisfied: pylint-plugin-utils<0.8,>=0.7 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.7)
Requirement already satisfied: requirements-detector>=1.0.3 in c:\program files\python 3.11\lib\site-packages (from prospector) (1.1.0)
Requirement already satisfied: setoptconf-tmp<0.4.0,>=0.3.1 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.3.1)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in c:\program files\python 3.11\lib\site-packages (from prospector) (0.10.2)
Requirement already satisfied: astroid>=1.0 in c:\program files\python 3.11\lib\site-packages (from pylint-celery==0.3->prospector) (2.15.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\program files\python 3.11\lib\site-packages (from GitPython<4.0.0,>=3.1.27->prospector) (4.0.10)
Requirement already satisfied: flake8-polyfill<2,>=1.0.2 in c:\program files\python 3.11\lib\site-packages (from pep8-naming<=0.10.0,>=0.3.3->prospector) (1.0.2)
Requirement already satisfied: snowballstemmer>=2.2.0 in c:\program files\python 3.11\lib\site-packages (from pydocstyle>=2.0.0->prospector) (2.2.0)
Requirement already satisfied: platformdirs>=2.2.0 in c:\program files\python 3.11\lib\site-packages (from pylint>=2.8.3->prospector) (3.2.0)
Requirement already satisfied: isort<6,>=4.2.5 in c:\program files\python 3.11\lib\site-packages (from pylint>=2.8.3->prospector) (5.12.0)
Requirement already satisfied: tomlkit>=0.10.1 in c:\program files\python 3.11\lib\site-packages (from pylint>=2.8.3->prospector) (0.11.7)
Requirement already satisfied: dill>=0.3.6 in c:\program files\python 3.11\lib\site-packages (from pylint>=2.8.3->prospector) (0.3.6)
Requirement already satisfied: colorama>=0.4.5 in c:\program files\python 3.11\lib\site-packages (from pylint>=2.8.3->prospector) (0.4.6)
Requirement already satisfied: poetry-semver<0.2.0,>=0.1.0 in c:\program files\python 3.11\lib\site-packages (from requirements-detector>=1.0.3->prospector) (0.1.0)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in c:\program files\python 3.11\lib\site-packages (from astroid>=1.0->pylint-celery==0.3->prospector) (1.9.0)
Requirement already satisfied: wrapt<2,>=1.14 in c:\program files\python 3.11\lib\site-packages (from astroid>=1.0->pylint-celery==0.3->prospector) (1.15.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\program files\python 3.11\lib\site-packages (from gitdb<5,>=4.0.1->GitPython<4.0.0,>=3.1.27->prospector) (5.0.0)
```

As you can see, I have all the latest versions installed. I have `pylint-django 2.5.3`.

**Comment by PedanticHacker** [comment]
Perhaps `prospector` uses `pylint` by targeting the old API of `pylint`. I think `prospector` is to blame here, not `pylint`.

**Comment by PedanticHacker** [comment]
Uhm, it is working now. I have no idea why it is working now. I ran `prospector` again just to give you the stacktrace, but now it worked. I have used the same command and haven't altered anything. Oh well, computers, who would understand them.

**Comment by PedanticHacker** [comment]
Sorry for the noise.
