### ISSUE TITLE
"Module 'numpy' has no ... member" error even with extension-pkg-whitelist=numpy set in pylint.rc

### ISSUE THREAD

**Issue by mpconte** [PyCQA/pylint#779]
I'm always receiving "Module 'numpy' has no member" error when I run pylint on my code, even though I have set

extension-pkg-whitelist=numpy
in my pylint.rc file

Numpy version = 1.5.2 
Astroid version = 1.4.3

**Comment by PCManticore** [comment]
Can you post an example for which you get the error?

**Comment by mpconte** [comment]
import numpy as np
dtype = np.float64


Pylint says:
Module 'numpy' has no 'float64' member

It does this for every other numpy dtype

**Comment by mpconte** [comment]
I'm also getting the same issue with pylint versions
**1.5.3** and **1.5.4**

**Comment by PCManticore** [comment]
I didn't have time to look into this just yet, but I presume that astroid.brain can't find the place where float64 is created (https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_numpy.py). What could move this forward would be to see where exactly np.float64 is defined and what's different about in in brain_numpy.py. With this information, we might modify brain_numpy accordingly.

**Comment by Titan-C** [comment]
I have this issue for all numpy functions as if 'extension-pkg-whitelist=numpy' would have no influence. pylint version, astroid 1.4.4

**Comment by PCManticore** [comment]
I'm not sure if all of them are like that, but there are some of them which are generated dynamically somewhere around in this file https://github.com/numpy/numpy/blob/master/numpy/core/numerictypes.py. extension-pkg-whitelist does not help in this case, but providing some hints would lead to a better result.

**Comment by pgdr** [comment]
Also affects pylint 1.6.5, even with `--extension-pkg-whitelist=numpy`  On file
```python
import numpy
numpy.float64
```
the output (incorrectly) is:
```
$ python -m pylint -E --extension-pkg-whitelist=numpy ex.py
************* Module ex
E:  2, 0: Module 'numpy' has no 'float64' member (no-member)
```

**Comment by GH1995** [comment]
me too
```
pylint 1.6.4, 
astroid 1.4.9
```
and in vim with `w0rp/ale`.
It shows `E1101: (no-member) Module 'numpy.random' has no 'randint' member`.

**Comment by pgdr** [comment]
@PCManticore is this anything that will be prioritized?  Do you have any idea what can be done to fix this issue?

I'm thinking especially getting `extension-pkg-whitelist` to be respected, not fixing the issue with mislabeling the numpy members as non-members.

**Comment by PCManticore** [comment]
``extension-pkg-whitelist`` does something different than what it would suggest. Since there are some bits of numpy written in C, pylint tries to import them in order to built an AST from a live object. This, of course, has some security implications and might not be desired at all, which is why these modules are exempted through a flag, e.g ``extension-pkg-whitelist``. The problem is that those members are added in pure Python code, using dynamic features of Python, such as ``globals`` modifications and whatnot, which don't fall in the scope of ``extension-pkg-whitelist``. And it is also pretty hard to understand by a static analysis tool nevertheless. 
This issue will probably get some priority at some point, as you can see it is scheduled for 2.0 milestone, but I can't promise anything until that point.
The problem can be solved, most probably, by a brain tip in astroid, but it requires someone that knows numpy internals well enough and it also requires a good enough solution (e.g only adding the correct members to numpy's module that patches itself with these dynamically generated members). As such, I didn't have enough time to work on this.

**Comment by gergelypolonkai** [comment]
As a workaround, I have created a small PyLint plugin, which will silence such warnings:

``` python
from astroid import MANAGER
from astroid import scoped_nodes

import numpy

def register(linter):
    pass

def transform(modu):
    if modu.name == 'numpy':
        for f in numpy.__dict__.keys():
            modu.locals[f] = [scoped_nodes.Class(f, None)]

MANAGER.register_transform(scoped_nodes.Module, transform)
```

**Comment by sam-s** [comment]
still present with
```
pylint 1.7.1, 
astroid 1.5.3
```

**Comment by Cartucho** [comment]
still present with:
```
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
```

**Comment by marmistrz** [comment]
Confirming:
```
pylint 1.7.2, 
astroid 1.5.3
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
```

**Comment by marmistrz** [comment]
The same happens with `twisted.internet.reactor`: 
```
from twisted.internet.reactor import run
```
causes an error:
```
E:  1, 0: No name 'run' in module 'twisted.internet.reactor' (no-name-in-module)
```
Pylint:
```
pylint 1.7.2, 
astroid 1.5.3
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
```

**Comment by awav** [comment]
I have same issue on `np.float32` | `np.float64`

* `numpy == 1.13.1`
* `pylint == 1.7.2`

**Comment by Jacob-Baldwin** [comment]
I am also having this issue with Levenshtein. Any fix?

**Comment by AWhetter** [comment]
As @PCManticore has previously mentioned, there is nobody who knows enough about both numpy and astroid to fix this.

I haven't tested but you should be able to add numpy to `ignored-modules` to workaround this.

**Comment by DavidBAEpstein** [comment]
I added

ignored-modules=numpy

to my ~/.pylintrc, and I still get a no-member error on numpy.random.randint

**Comment by AWhetter** [comment]
Try `numpy*` or maybe `numpy.*`?

**Comment by dinio31** [comment]
The best solution we have found so far, using only parameters in `.pylintrc` file :

- allow pylint to load the numpy C libraries by whitelisting it (`extension-pkg-whitelist` parameter)
- list all the dynamically generated numpy members in the `generated-members` parameter

```
[MASTER]
...
extension-pkg-whitelist=numpy
...
[TYPECHECK]
...
generated-members=numpy.uint32,numpy.float32
```
Using the following piece of code:
```
import numpy

a = numpy.random.randint(10, 20, (numpy.uint32(10)))
z = numpy.zeros_like(a)
f = numpy.full((2, 2), numpy.float32(3))
s = numpy.square(a)

z_no_arg = numpy.zeros_like()
s_no_arg = numpy.square()
```
When `extension-pkg-whitelist` and `generated-members` are left empty, `pylint ` issues the following errors:

```
E:  3, 4: Module 'numpy.random' has no 'randint' member (no-member)
E:  3,34: Module 'numpy' has no 'uint32' member (no-member)
E:  5,23: Module 'numpy' has no 'float32' member (no-member)
E:  6, 4: Module 'numpy' has no 'square' member (no-member)
E:  8,11: No value for argument 'a' in function call (no-value-for-parameter)
E:  9,11: Module 'numpy' has no 'square' member (no-member)
```
Note that `zeros_like` function is correctly recognized.

When specifying `extension-pkg-whitelist=numpy` only, some members (`randint` and `square`) are recognized but the following errors remains:

```
E:  3,34: Module 'numpy' has no 'uint32' member (no-member)
E:  5,23: Module 'numpy' has no 'float32' member (no-member)
E:  8,11: No value for argument 'a' in function call (no-value-for-parameter)
```
Adding `generated-members=numpy.uint32,numpy.float32` leads to only one error left, which is correctly identified:
```
E:  8,11: No value for argument 'a' in function call (no-value-for-parameter)
```

However there is another potential pylint bug when a package has been imported with an alias (this is commonly done in the numpy tutorials). With the following piece of code:
```
import numpy as np

a = np.random.randint(10, 20, (np.uint32(10)))
z = np.zeros_like(a)
f = np.full((2, 2), np.float32(3))
s = np.square(a)

z_no_arg = np.zeros_like()
s_no_arg = np.square()
```
float32 and uint32 are not recognized. This can be solved by appending the aliased members names in `generated-members`, which results in the final `.pylintrc` modifications:
```
[MASTER]
...
extension-pkg-whitelist=numpy
...
[TYPECHECK]
...
generated-members=numpy.uint32,numpy.float32,np.uint32,np.float32
```
Tested with versions:
```
python==2.7.13
numpy==1.10.4
pylint==1.6.4
```

**Comment by akorp** [comment]
Have the same issue with numpy and cv2
numpy 1.11.1
cv2 3.1.0
pylint 1.5.4, 
astroid 1.4.7
Python 3.5.2

Had to use the solution of dinio31 to get rid of the mistakes

**Comment by livc** [comment]
Same issue, any update?

**Comment by wq1308786830** [comment]
Same issue with `np.float32(np.random.rand(2, 100))`：

> [pylint] E1101:Module 'numpy.random' has no 'rand' member; maybe 'ranf'?

> [pylint] E1101:Module 'numpy' has no 'float32' member

**Comment by XericZephyr** [comment]
Same issue here.

**Comment by alapini** [comment]
Same Issue in PyLint for VSCode.

**Comment by hippo91** [comment]
Hi all,
Those problems should be solved now thanks to https://github.com/PyCQA/astroid/pull/461.
Can you confirm please?

**Comment by repentsinner** [comment]
Looks like the changes are live as of astroid 1.6.0. Just deleted `#pylint: disable=E1101` from an `np.random.seed()` call and pylint in VSCode no longer complains.

Many thanks @hippo91 and @PCManticore!

**Comment by dinio31** [comment]
Thanks @hippo91 for the great work!
However it does not solve all our problems, described in my previous post above. Using the same piece of code :
```
import numpy

a = numpy.random.randint(10, 20, (numpy.uint32(10)))
z = numpy.zeros_like(a)
f = numpy.full((2, 2), numpy.float32(3))
s = numpy.square(a)

z_no_arg = numpy.zeros_like()
s_no_arg = numpy.square()
```
and with both `extension-pkg-whitelist` and `generated-members` left empty in  `.pylintrc` file, `pylint ` still issues the following errors:

```
E:  3,34: Module 'numpy' has no 'uint32' member; maybe 'int32'? (no-member)
E:  5,23: Module 'numpy' has no 'float32' member (no-member)
E:  8,11: No value for argument 'a' in function call (no-value-for-parameter)
E:  9,11: No value for argument 'x' in function call (no-value-for-parameter)
```
It is thus still necessary to add `generated-members=numpy.uint32,numpy.float32` in  `.pylintrc` to get rid of the first two errors and get the expected result:
```
E:  8,11: No value for argument 'a' in function call (no-value-for-parameter)
E:  9,11: No value for argument 'x' in function call (no-value-for-parameter)
```

The new Astroid release has thus removed the need to whitelist numpy in `.pylintrc`, but it is still necessary to declare the generated members.
Moreover this declaration must be made for all the possible aliases used for numpy (it is very common to find ``` import numpy as np``` in numpy tutorials). May be it comes from a different bug?

Tested with versions:
```
python==2.7.13
numpy==1.12.1
pylint==1.8.1
astroid==1.6.0
```

**Comment by hippo91** [comment]
Thanks for your answers.
@dinio31 i'm working on including all ``numpy`` numeric types inside ``astroid``'s ``numpy``  brain.
The problem is that they depend on the platform on which ``numpy`` is run.
I'm looking for a solution ...

**Comment by hippo91** [comment]
HI all, 
the problem of unknown types in numpy should be solved now thanks to https://github.com/PyCQA/astroid/pull/488 for 1.6 branch and https://github.com/PyCQA/astroid/pull/486 for master branch.
Can you confirm please?

**Comment by maddenp** [comment]
Apologies if I've missed a detail about the fix, but it seems that there are still problems:
```
~ % conda create -n foo -c conda-forge -c defaults --override-channels -y numpy pylint=1.8.1
[...]
~ % conda activate foo
(foo) ~ % cat test.py
''' test '''
import numpy
print(numpy.log)
print(numpy.float64)
(foo) ~ % python test.py 
<ufunc 'log'>
<class 'numpy.float64'>
(foo) ~ % pylint --extension-pkg-whitelist=numpy test.py
No config file found, using default configuration
************* Module test
E:  4, 6: Module 'numpy' has no 'float64' member (no-member)

---------------------------------------------------------------------
Your code has been rated at -6.67/10 (previous run: -15.00/10, +8.33)
```
That is, e.g., `numpy.log` is no longer flagged, but `numpy.float64` still is.

**Comment by pmspire** [comment]
I cleaned everything and re-ran the above test again with the same results. I have
```
(foo) ~ % conda list | grep astroid
astroid                   1.5.3                    py36_0    conda-forge
```

**Comment by hippo91** [comment]
@pmspire thanks again for your quick answer.
The problem comes from your ``astroid`` version. It should be at least 1.6.1.
Is it possible for you to update ``astroid`` to version 1.6.1 ?

**Comment by hippo91** [comment]
@pmspire i'll check ASAP, maybe this weekend.

**Comment by Marriaga** [comment]
astroid (1.6.1)
pylint (1.8.2)
"E1101:Module 'numpy' has no 'float32' member"

**Comment by repentsinner** [comment]
@hippo91 I don't think the fix is in 1.6.1; it's on 1.6.x but by my reading of https://github.com/PyCQA/astroid/pull/486 we're not going to see it until 1.6.2 which hasn't been released by @PCManticore yet?

**Comment by PCManticore** [comment]
Yes, 1.6.2 is not yet released, I'll do it today. Also folks please take some time to appreciate the tremendous work that @hippo91 is doing with this issue, this one wasn't easy and as a result of his work, numpy's support is getting top notch.

**Comment by wanghran** [comment]
astroid (1.6.1)
isort (4.3.4)
pylint (1.8.2)
numpy (1.14.2 )
E1101:Module 'numpy' has no 'float64' member

**Comment by PCManticore** [comment]
I just released pylint 1.8.3 and astroid 1.6.2, which includes all the fixes to numpy that @hippo91 worked on. I'm closing this issue, thank you so much @hippo91 for the hard work!

**Comment by dinio31** [comment]
I just tested these latest versions with the example I gave above and on my python projects.

No more need to declare numpy in the `extension-pkg-whitelist` and `generated-members` fields of `.pylintrc`! pylint now works like a charm with numpy!
And pylint immediately exhibited a bug in my code that was previously hidden by these `.pylintrc` settings!

Many thanks @hippo91 for the great work!
Thanks a lot @PCManticore for the releases!

**Comment by hippo91** [comment]
@dinio31 thank you for your reply!
It is always pleasant to know this work is useful.

**Comment by sam-s** [comment]
I still see `E1101, no-member: Module 'numpy' has no 'floating' member` with
```
pylint 1.9.1, 
astroid 1.6.4
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```
and
```
>>> np.version.version
'1.14.3'
>>> np.floating
<class 'numpy.floating'>
```
should I open a new issue?

**Comment by PCManticore** [comment]
@sam-s yes, please.

**Comment by BurakcanK** [comment]
The problem still persists with the 'cv2' module in vscode, even if I added `extension-pkg-whitelist=cv2` to the `.pylintrc`.

**Comment by PCManticore** [comment]
The numpy support has nothing to do with cv2. Please open a separate issue.

**Comment by BurakcanK** [comment]
@PCManticore Sorry, it was mentioned here once by @akorp, that's why I brought it up again.

**Comment by FlappyHeart** [comment]
Same issues here with cv2

pylint 1.9.2,
astroid 1.6.5
Python 3.6.5

**Comment by PaulStubbs** [comment]
Still broken with OpenCV v4:
OpenCV 4.0.0
VSCode 1.30.0
pylint 2.2.2
astroid 2.1.0
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

**Comment by hippo91** [comment]
@PaulStubbs thanks for the report.
What is exactly the problem please?
I'm not sure it deals with `numpy`.
If it is directly related to the `OpenCV` module, please open another issue.
Thank you again.

**Comment by hippo91** [comment]
@PaulStubbs 
Is your issue related to #2426 ?

**Comment by lai-bluejay** [comment]
If you don't want to add more config, please add this code to your config file, instead of 'whitelist'.


```json
{
"python.linting.pylintArgs": ["--generate-members"],
}
```
relevent question: [how-do-i-get-pylint-to-recognize-numpy-member](https://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members/54980614#54980614)

**Comment by afshinfard** [comment]
I am facing the same problem with updated pylint (2.148.0) for `numpy.linalg`.
Actually, I import `numpy` and `scipy` and use `scipy.linalg` in my code; and when I run pylint I get an error stating that ` E1101: Module 'numpy.linalg' has no 'blas' member (no-member)`.

**Comment by sam-s** [comment]
I see `Module 'numpy' has no 'float128' member` with 
```
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
```
(despite `extension-pkg-whitelist=numpy` which _does_ take care of `float64` et al)

Should I open a new issue?

**Comment by hippo91** [comment]
@sam-s, if i remember correctly, `float128` is not necessarily present on all platforms. Instead of trying to detect what kind of platform `numpy` is running on, `pylint`'s default is to emit such message.
I think it would need work that is not absolutely necessarily to handle such case.
What do you think about it?

**Comment by bjtho08** [comment]
> If you don't want to add more config, please add this code to your config file, instead of 'whitelist'.
> 
> ```json
> {
> "python.linting.pylintArgs": ["--generate-members"],
> }
> ```
> 
> relevent question: [how-do-i-get-pylint-to-recognize-numpy-member](https://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members/54980614#54980614)

That pylint option is incorrect and actually makes pylint silently fail, thus making it look as though there are no errors, ever. The correct snippet is:

```json
{
"python.linting.pylintArgs": ["--generated-members=numpy.*"],
}
```
However, this still does not work in VSCode. I am getting `Function 'logical_and' has no 'reduce' member` even though I am using

```
pylint 2.3.1
astroid 2.2.5
numpy 1.16.4
```

Should I open a new issue pertaining to this particular case of `no-member`?

**Comment by Alamnoor** [comment]
1. On VScode: CTRL + Shift + P
 2. Choose "Preferences: Open Settings (JSON)"
3.  Add this line into JSON file: "python.linting.pylintArgs": ["--generate-members"]

Done, it works for me

Note: Make sure you choose "Preferences: Open Settings (JSON)", not "Preferences: Open Default Settings (JSON)"

Setting File would look like

{
"workbench.iconTheme": "vscode-icons",
"python.dataScience.sendSelectionToInteractiveWindow": true,
"kite.showWelcomeNotificationOnStartup": false,
"python.dataScience.askForKernelRestart": false,
"python.dataScience.jupyterServerURI": "local",
"python.pythonPath": "/usr/bin/python3",
"workbench.colorTheme": "Monokai",
"vsicons.dontShowNewVersionMessage": true,
"python.linting.pylintArgs": ["--generate-members"] }

**Comment by bjtho08** [comment]
> 1. On VScode: CTRL + Shift + P
> 2. Choose "Preferences: Open Settings (JSON)"
> 3. Add this line into JSON file: "python.linting.pylintArgs": ["--generate-members"]
> 
> Done, it works for me

@Alamnoor I can assure you that it's not working. Try making a deliberate error and run pylint with that option. You will find out that you still get zero errors. The reason is that the option you added is not a real pylint option and it will cause pylint to fail silently when run through vscode. You can verify this by running pylint manually from the command line with that option and you will see the suppressed error. See my comment above for an explanation.
